export const SHOP_TYPE = {
    UPDATA_SHOPDATA: 'UPDATA_SHOPDATA',
    SHOPDATA_FETCHING_START:'SHOPDATA_FETCHING_START',
    SHOPDATA_FETCHING_SUCCESS:'SHOPDATA_FETCHING_SUCCESS',
    SHOPDATA_FETCHING_FAILED:'SHOPDATA_FETCHING_FAILED',
}

